// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg4qESxFd6rlOZpkQy88MXD7pk5uaYUW4',
    appId: '1:885253687379:web:16017f27af0b734ae61ea6',
    messagingSenderId: '885253687379',
    projectId: 'task-manager-6c79f',
    authDomain: 'task-manager-6c79f.firebaseapp.com',
    storageBucket: 'task-manager-6c79f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5WvhbGNTl-U1-Gm40mL77M0B4ItC7hpg',
    appId: '1:885253687379:android:58bd7c6335a443f5e61ea6',
    messagingSenderId: '885253687379',
    projectId: 'task-manager-6c79f',
    storageBucket: 'task-manager-6c79f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4UnJwduSBr9NdZA-Ghka1uO2NBYW6njw',
    appId: '1:885253687379:ios:1fb029d91d1f2edce61ea6',
    messagingSenderId: '885253687379',
    projectId: 'task-manager-6c79f',
    storageBucket: 'task-manager-6c79f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4UnJwduSBr9NdZA-Ghka1uO2NBYW6njw',
    appId: '1:885253687379:ios:1fb029d91d1f2edce61ea6',
    messagingSenderId: '885253687379',
    projectId: 'task-manager-6c79f',
    storageBucket: 'task-manager-6c79f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg4qESxFd6rlOZpkQy88MXD7pk5uaYUW4',
    appId: '1:885253687379:web:6c88e6e1fd8d000fe61ea6',
    messagingSenderId: '885253687379',
    projectId: 'task-manager-6c79f',
    authDomain: 'task-manager-6c79f.firebaseapp.com',
    storageBucket: 'task-manager-6c79f.firebasestorage.app',
  );
}
